### PR TITLE
Fix coredump in case of Pleiades data provider

### PR DESCRIPTION
**Pull request by drons**

### CODE REVIEW

**Comment by drons** [comment]
@setsmdeveloper, @JudyGardiner 
Do you have any suggestions for this PR?

**Comment by setsmdeveloper** [comment]
Pleiades problem is solved with new version 3.4.3. Please test it.
drons : Would you introduce me who you are for future work ?

**Comment by drons** [comment]
>Pleiades problem is solved with new version 3.4.3. Please test it.

Good news. I'm test it.

>drons : Would you introduce me who you are for future work ?

@setsmdeveloper I'm answer by email

**Comment by drons** [comment]
@setsmdeveloper I.m test new version 3.4.3 with Pleiades imagery. 
Bug is fixed. 
Request can be closed.
Thanks!

**Pull request closed without merging**
